# Generated by Django 4.1.3 on 2022-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('principal', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
